### ISSUE TITLE
PC Support

### ISSUE THREAD

**Issue by mattcroftuk** [InkedCurtis/FUT19-Buyer#1]
Any intentions for yourself to add PC Support, i've modified the code and managed to get it working for PC, would you like me to submit a PR for this?

I also came across a few other issues with the code when updating to work for PC, would you like me to submit those as Issues?

**Comment by InkedCurtis** [comment]
Sure, that'd be great if you could do so!

**Comment by JhonMaya** [comment]
Inked the risk is high to take a ban?

**Comment by InkedCurtis** [comment]
@JhonMaya that's solely based on how heavy you're running; the system is developed to mimic the WebApp as closely as possible
