### ISSUE TITLE
email adress must be unique

### ISSUE THREAD

**Issue by lvvkas** [InkedCurtis/FUT19-Buyer#10]
I added an account with that email, deleted it... now it won't add my email anymore

**Comment by InkedCurtis** [comment]
This issue is fixed in one of my latest commits, please re-clone & setup again

**Comment by gianemi2** [comment]
You have to delete this row manually.
`mysql -u INSERT_USERNAME -p INSERT_PASSWORD`
mysql > `show databases;`
Read the name of the database.
mysql > `use INSERT_DATABASE_NAME;`
mysql > `SELECT * FROM users;`
Read the ID of your user (if is the first user created the ID should be 1)
mysql > `DELETE FROM users WHERE id = INSERT_ID;`
