### ISSUE TITLE
Stopped working after patch

### ISSUE THREAD

**Issue by albertosoho** [InkedCurtis/FUT19-Buyer#18]
Hi, it seems it stopped working after last night's patch from fifa.

I've been using it the last three weeks without a problem.

Weird thing is that i'm not getting error messages or anything like that.

**Comment by InkedCurtis** [comment]
Can you confirm this is still the case?

**Comment by albertosoho** [comment]
Yes, it is.

[https://imgur.com/BT9sSMj](url)

Last trade was right before the latest fifa update. I have two more installs (one locally), all of them stopped working.

**Comment by InkedCurtis** [comment]
@albertosoho I can confirm this isn't the case with the premium version
