### ISSUE TITLE
.env.example not found

### ISSUE THREAD

**Issue by lvvkas** [InkedCurtis/FUT19-Buyer#2]
php -r "copy('/var/www/html/.env.example', '/var/www/html/.env');"
PHP Warning:  copy(/var/www/html/.env.example): failed to open stream: No such file or directory in Command line code on line 1

**Comment by GorillazJS** [comment]
> Did you clone the repository before running this?

is it possible to run on localhost with mamp?

**Comment by InkedCurtis** [comment]
Yes, but configuration would not be the same as a LAMP setup, this meaning your commands would be different

**Comment by GorillazJS** [comment]
> Yes, but configuration would not be the same as a LAMP setup, this meaning your commands would be different
ok thx!
Origin plataform are working ?

**Comment by InkedCurtis** [comment]
Correct, as far as I'm aware
