### ISSUE TITLE
How to start the bot?

### ISSUE THREAD

**Issue by lvvkas** [InkedCurtis/FUT19-Buyer#6]
How do I start the bot?

**Comment by InkedCurtis** [comment]
The bot starts as soon as you've added the required command to your crontab as explained in the instructions

**Comment by lvvkas** [comment]
Its already started, but in the actual dashboard nothing happens

**Comment by lvvkas** [comment]
I added my account and it says offline

**Comment by gianemi2** [comment]
run `php artisan fix_accounts:cron`
