### ISSUE TITLE
Split the Buy Command

### ISSUE THREAD

**Issue by mattcroftuk** [InkedCurtis/FUT19-Buyer#7]
Is it possible to split the buy command so that the tradepile can be handled away from the autobuy?

Would be nice to have it just handle the tradepile and buy seperate.

**Comment by InkedCurtis** [comment]
I'd highly recommend against that, means having two processes running at the same time for the same account

**Comment by mattcroftuk** [comment]
I get what you mean, however sometimes i dont want to purchase anymore players and only want my trades to be updated.

With the way the current `autobuyer_status` flag works, if you disable it then it does not update the trades, so maybe add a way so that disabling the autobuyer does not effect the trades?
