### ISSUE TITLE
Request per minute issue

### ISSUE THREAD

**Issue by mattcroftuk** [InkedCurtis/FUT19-Buyer#8]
Seems that the request per issue causes `temporary_bans` when handling the trade pile, this seems to be solved if i add a `sleep()` after it does some tradepile actions

**Comment by gianemi2** [comment]
@mattcroftuk  In which line should I add this code? I get temporary ban as soon as i put something in tradepile.

**Comment by InkedCurtis** [comment]
238b1dabe63d4e8c1e58177a509004e60f6ae571 should have fixed this issue

**Comment by cookiekop** [comment]
got the same problem!
