### ISSUE TITLE
Autobuyer flag on players

### ISSUE THREAD

**Issue by mattcroftuk** [InkedCurtis/FUT19-Buyer#9]
Is it possible to get an flag on players to enable auto-buy specifically for them?

Also an option to not sell if below the original purchase price check would be ideal as seem to be losing money this way.

**Comment by InkedCurtis** [comment]
Can you provide a better understanding on what you mean in regards to "flag"?

**Comment by mattcroftuk** [comment]
![players](https://user-images.githubusercontent.com/11648395/47514295-edf89800-d877-11e8-9c91-784c72925cbb.png)

Yea maybe a flag is not the right term.

The first issue i think has been solved by your soft deletes fix i believe, but i was suggesting a way to enable a player specifically that you want to purchase, the original issue was when you delete a player it then can no longer handle the current tradepile with those players, but it would continue to purchase them if you left the player in the list.

The second issue is in more depth

So an example of the issue im having is, these players were bought at X price then later on the prices updates and they were sold at the curreny sell now price, would be good if we had a way of saying if the sell now price is lower than the bought price then use the bought price etc.

Hope that makes more sense
